name: Enhanced AI Bug Router

on:
  schedule:
    # Run daily at 8:00 AM Malaysia Time (00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'false'

jobs:
  enhanced-bug-router:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'scripts/ai-bug-router-enhanced/package-lock.json'
          
      - name: Validate Security Configuration
        run: |
          echo "🔐 Validating security setup..."
          # Check that no secrets are hardcoded in files
          if grep -r "sk-" scripts/ 2>/dev/null | grep -v "your-" | grep -v "example" | grep -v "placeholder"; then
            echo "❌ Potential OpenAI key found in code!"
            exit 1
          fi
          if grep -r "xoxb-\|xoxp-" scripts/ 2>/dev/null | grep -v "your-" | grep -v "example" | grep -v "placeholder"; then
            echo "❌ Potential Slack token found in code!"
            exit 1
          fi
          if grep -r "pk_.*_" scripts/ 2>/dev/null | grep -v "your-" | grep -v "example" | grep -v "placeholder"; then
            echo "❌ Potential ClickUp token found in code!"
            exit 1
          fi
          echo "✅ Security validation passed - no hardcoded secrets detected"
          
      - name: Install dependencies
        run: |
          cd scripts/ai-bug-router-enhanced
          npm ci
          
      - name: Run Enhanced AI Bug Router
        env:
          # Sensitive API Keys - Properly secured via GitHub Secrets
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLICKUP_API_TOKEN: ${{ secrets.CLICKUP_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Public configuration (safe to expose)
          SLACK_CHANNEL: C02GDJUE8LW
          NODE_ENV: production
          
          # Enhanced Router Configuration
          CLICKUP_TEAM_ID: 2627356
          CLICKUP_BUG_LIST_ID: 900501824745
          SLACK_TEAM_ID: bijimereka
          SLACK_DEV_CHANNEL: C02GDJUE8LW
          
          # AI Settings
          AI_CONFIDENCE_THRESHOLD: 0.7
          ENABLE_AI_CODE_GENERATION: true
          ENABLE_USER_EDUCATION: true
          ENABLE_DUPLICATE_PREVENTION: true
          ENABLE_EMOJI_FEEDBACK: true
          ENABLE_DAILY_WORKFLOW: true
          MAX_DAILY_ISSUES: 50
          
          # Logging
          LOG_LEVEL: info
          ENABLE_DETAILED_LOGGING: true
          ENABLE_METRICS: true
          
        run: |
          cd scripts/ai-bug-router-enhanced
          if [ "${{ github.event.inputs.test_mode }}" = "true" ]; then
            echo "🧪 Running in test mode..."
            node test-demo.js
          else
            echo "🚀 Running daily enhanced workflow..."
            node main.js daily
          fi
          
      - name: Health Check
        if: always()
        env:
          # Sensitive API Keys - Required for health check
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLICKUP_API_TOKEN: ${{ secrets.CLICKUP_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          cd scripts/ai-bug-router-enhanced
          echo "🏥 Running health check..."
          node main.js health || echo "Health check failed - check configuration"
          
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-bug-router-logs
          path: |
            scripts/ai-bug-router-enhanced/logs/
            scripts/ai-bug-router-enhanced/artifacts/
          retention-days: 7
