name: Daily Job Creation Tests

on:
  # Run daily at 9 AM UTC (adjust timezone as needed)
  schedule:
    - cron: '0 9 * * *'  # 9 AM UTC daily
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      test_env:
        description: 'Test Environment'
        required: true
        default: 'live'
        type: choice
        options:
          - dev
          - live
          - both

jobs:
  job-creation-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # Focus on main browsers for job creation
        browser: [chromium, firefox]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Job Creation Test
      run: npx playwright test mereka-automation/job/job-creation/create-job-post.spec.ts --project=${{ matrix.browser }} --workers=1
      env:
        TEST_ENV: ${{ github.event.inputs.test_env || 'live' }}
        CI: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: job-creation-report-${{ matrix.browser }}
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: job-creation-videos-${{ matrix.browser }}
        path: test-results/
        retention-days: 7

  notify:
    needs: job-creation-test
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Send Slack notification on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        channel: '#qa-alerts'
        text: 'Daily Job Creation tests failed! Check the logs for details.'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Send Slack notification on success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        channel: '#qa-alerts'
        text: 'Daily Job Creation tests passed successfully!'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Daily Job Creation Test Failed - ' + new Date().toISOString().split('T')[0],
            body: 'The daily job creation test failed. Please check the workflow logs for details.\n\n' +
                  'Workflow: ' + context.workflow + '\n' +
                  'Run: ' + context.runNumber,
            labels: ['bug', 'automation', 'job-creation']
          }) 