name: Publish Test Reports

on:
  workflow_run:
    workflows: ["Daily Job Creation Tests"]
    types:
      - completed

jobs:
  publish-reports:
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Download test reports
      uses: actions/download-artifact@v4
      with:
        name: job-creation-report-chromium
        path: ./reports/chromium/
    
    - name: Download test reports (Firefox)
      uses: actions/download-artifact@v4
      with:
        name: job-creation-report-firefox
        path: ./reports/firefox/
      continue-on-error: true
    
    - name: Create index page
      run: |
        mkdir -p ./reports
        cat > ./reports/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <title>Mereka Test Reports</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .container { max-width: 800px; margin: 0 auto; }
            .report-link { display: block; padding: 10px; margin: 10px 0; background: #f5f5f5; border-radius: 5px; text-decoration: none; color: #333; }
            .report-link:hover { background: #e0e0e0; }
            .timestamp { color: #666; font-size: 0.9em; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>Mereka Automation Test Reports</h1>
            <p class="timestamp">Last updated: $(date)</p>
            <a href="./chromium/index.html" class="report-link">
              <strong>Chromium Test Results</strong><br>
              <small>Job Creation Test - Chrome Browser</small>
            </a>
            <a href="./firefox/index.html" class="report-link">
              <strong>Firefox Test Results</strong><br>
              <small>Job Creation Test - Firefox Browser</small>
            </a>
          </div>
        </body>
        </html>
        EOF
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports 